
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup
import shutil
import sys
import datetime
import fileinput

version_string = "4.28"

#
# Modify the build_info text file to have the current build date, number and correct version
#

APP = ['hamclock_launcher.py']

if sys.platform == 'darwin':
    import py2app.recipes
    class PIL_recipe:
        def check(self, cmd, mf):
            m = mf.findNode("PIL")
            if m is None or m.filename is None:
                return None

            # Exclude from site-packages.zip
            return {"packages": ["PIL"]}


    py2app.recipes.PIL = PIL_recipe()

    Plist = dict(
        CFBundleName='HamClockLauncher',
        CFBundleGetInfoString='HamClockLauncher',
        CFBundleShortVersionString='4.28',
        NSHumanReadableCopyright='HamClockLauncher © 2025-2026, Hubert Hickman'
        )

    print(Plist)
    OPTIONS = {'argv_emulation': False,
               'iconfile': 'hamclock_icons.icns',
               'resources': ['hamclock_bin', 'release_notes.html', 'HamClockKey.pdf'],
                             #'cacert.pem'],
               'plist': Plist,
               'includes': ['six', 'packaging', 'packaging.version','wx',
                            'packaging.specifiers', 'packaging.requirements', 'appdirs', 'requests', 'OpenSSL',
                            'pyasn1', 'certifi', 'ndg-httpsclient'],
               'packages': ['wx']
              # 'codesign_entitlements': 'entitlements.plist'

               }

    setup(
        app=APP,
        #data_files=DATA_FILES,
        options={'py2app': OPTIONS},
        setup_requires=['py2app'],

    )
